version: '3'

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"

  frontend:
    build: ./src
    container_name: frontend-container
    ports:
      - "80:80"
